name: Confirm Secrets

on:
  workflow_call:
    inputs:
      secret-name:
        type: string
        description: 'シークレット名'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Echo secrets
        run: |
          echo "secret name: ${{ inputs['secret-name'] }}"
          echo "secret key: ${{ secrets[format('{0}', inputs.secret-name)] }}"
